apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-producer-deployment
  labels:
    app: spring-boot-producer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-boot-producer
  template:
    metadata:
      labels:
        app: spring-boot-producer
    spec:
      containers:
      - name: spring-boot-consumer
        image: marceloquadros/spring-boot-producer
        ports:
        - containerPort: 8080
